### PR TITLE
Use Suave

### PR DESCRIPTION
**Pull request by panesofglass**
Unfortunately, I'm seeing socket errors in the console log, which I have not yet managed to successfully copy. cc: @haf @ademar

I would prefer this be made into a script, a la https://github.com/tpetricek/suave-xplat-gettingstarted/blob/master/build.fsx. cc: @jeroldhaas

### CODE REVIEW

**Comment by haf** [comment]
I have some time this weekend to have a look at the test cases in the PR we've put together. If we can keep this open till then, it would help me greatly.

**Comment by panesofglass** [comment]
@haf absolutely! I will probably be otherwise employed until the end of the weekend myself. I have not yet successfully run WebSharper on Suave. I haven't looked closely enough to see whether this problem is the same as with Freya or not.

**Comment by jeroldhaas** [comment]
Can you paste the log with socket errors? Might help diagnose the matter...

**Comment by panesofglass** [comment]
Yep; trying to do that now.

**Comment by panesofglass** [comment]
```
C:\Users\ryan\Code\c4fsharp [feature/suave]> .\src\c4fsharp\bin\c4fsharp.exe C:\Users\ryan\Code\c4fsharp\src\c4fsharp http://localhost:8083
[V] 2015-11-25T19:21:32.2087187Z: initialising BufferManager with 827392 bytes [Suave.Socket.BufferManager]
[I] 2015-11-25T19:21:32.2555618Z: listener started in 46.871 ms with binding 127.0.0.1:8083 [Suave.Tcp.tcpIpServer]
[V] 2015-11-25T19:21:45.4106014Z: 127.0.0.1 connected, total: 2 clients [Suave.Tcp.tcpIpServer.job]
[V] 2015-11-25T19:21:45.4106014Z: 127.0.0.1 connected, total: 2 clients [Suave.Tcp.tcpIpServer.job]
[V] 2015-11-25T19:21:45.4185995Z: reserving buffer: 802816, free count: 98 [Suave.Tcp.tcpIpServer.job] [Suave.Socket.BufferManager]
[V] 2015-11-25T19:21:45.4185995Z: reserving buffer: 811008, free count: 99 [Suave.Tcp.tcpIpServer.job] [Suave.Socket.BufferManager]
[V] 2015-11-25T19:21:45.4266168Z: -> processor [Suave.Web.httpLoop.loop]
[V] 2015-11-25T19:21:45.4266168Z: -> processor [Suave.Web.httpLoop.loop]
[V] 2015-11-25T19:21:45.4285999Z: reading first line of request [Suave.Web.processRequest]
[V] 2015-11-25T19:21:45.4285999Z: reading first line of request [Suave.Web.processRequest]
[V] 2015-11-25T19:21:45.4436550Z: reserving buffer: 794624, free count: 97 [Suave.Web.readMoreData] [Suave.Socket.BufferManager]
[V] 2015-11-25T19:21:45.4436550Z: reserving buffer: 786432, free count: 96 [Suave.Web.readMoreData] [Suave.Socket.BufferManager]
[V] 2015-11-25T19:21:45.4436550Z: 127.0.0.1 connected, total: 3 clients [Suave.Tcp.tcpIpServer.job]
[V] 2015-11-25T19:21:45.4436550Z: 127.0.0.1 connected, total: 4 clients [Suave.Tcp.tcpIpServer.job]
[V] 2015-11-25T19:21:45.4436550Z: reserving buffer: 778240, free count: 95 [Suave.Tcp.tcpIpServer.job] [Suave.Socket.BufferManager]
[V] 2015-11-25T19:21:45.4436550Z: reserving buffer: 770048, free count: 94 [Suave.Tcp.tcpIpServer.job] [Suave.Socket.BufferManager]
[V] 2015-11-25T19:21:45.4592290Z: -> processor [Suave.Web.httpLoop.loop]
[V] 2015-11-25T19:21:45.4592290Z: reading first line of request [Suave.Web.processRequest]
[V] 2015-11-25T19:21:45.4592290Z: reserving buffer: 761856, free count: 93 [Suave.Web.readMoreData] [Suave.Socket.BufferManager]
[V] 2015-11-25T19:21:45.4592290Z: 127.0.0.1 connected, total: 5 clients [Suave.Tcp.tcpIpServer.job]
[V] 2015-11-25T19:21:45.4592290Z: reserving buffer: 753664, free count: 92 [Suave.Tcp.tcpIpServer.job] [Suave.Socket.BufferManager]
[V] 2015-11-25T19:21:45.4592290Z: -> processor [Suave.Web.httpLoop.loop]
[V] 2015-11-25T19:21:45.4592290Z: -> processor [Suave.Web.httpLoop.loop]
[V] 2015-11-25T19:21:45.4592290Z: reading first line of request [Suave.Web.processRequest]
[V] 2015-11-25T19:21:45.4592290Z: reading headers [Suave.Web.processRequest]
[V] 2015-11-25T19:21:45.4592290Z: reserving buffer: 745472, free count: 91 [Suave.Web.readMoreData] [Suave.Socket.BufferManager]
[V] 2015-11-25T19:21:45.4592290Z: reading first line of request [Suave.Web.processRequest]
[V] 2015-11-25T19:21:45.4592290Z: reserving buffer: 737280, free count: 90 [Suave.Web.readMoreData] [Suave.Socket.BufferManager]
[V] 2015-11-25T19:21:45.4749664Z: freeing buffer: 786432, free count: 91 [Suave.Web.split] [Suave.Socket.BufferManager]
[V] 2015-11-25T19:21:45.4749664Z: parsing post data [Suave.Web.processRequest]
[V] 2015-11-25T19:21:45.4904779Z: <- processor [Suave.Web.httpLoop.loop]
[V] 2015-11-25T19:21:45.5905605Z: yielding to OWIN middleware [Suave.Owin]
[V] 2015-11-25T19:21:45.6530699Z: 127.0.0.1 connected, total: 6 clients [Suave.Tcp.tcpIpServer.job]
[V] 2015-11-25T19:21:45.6530699Z: reserving buffer: 786432, free count: 90 [Suave.Tcp.tcpIpServer.job] [Suave.Socket.BufferManager]
[V] 2015-11-25T19:21:45.6530699Z: -> processor [Suave.Web.httpLoop.loop]
[V] 2015-11-25T19:21:45.6530699Z: reading first line of request [Suave.Web.processRequest]
[V] 2015-11-25T19:21:45.6530699Z: reserving buffer: 729088, free count: 89 [Suave.Web.readMoreData] [Suave.Socket.BufferManager]
[V] 2015-11-25T19:21:45.8873953Z: suave back in control [Suave.Owin]
[V] 2015-11-25T19:21:45.9029782Z: writing preamble [Suave.Owin]
[V] 2015-11-25T19:21:45.9029782Z: writing body [Suave.Owin]
[V] 2015-11-25T19:21:45.9366230Z: 'Connection: keep-alive' recurse [Suave.Web.httpLoop.loop]
[V] 2015-11-25T19:21:45.9376150Z: -> processor [Suave.Web.httpLoop.loop]
[V] 2015-11-25T19:21:45.9376150Z: reading first line of request [Suave.Web.processRequest]
[V] 2015-11-25T19:21:45.9386111Z: reserving buffer: 720896, free count: 88 [Suave.Web.readMoreData] [Suave.Socket.BufferManager]
[V] 2015-11-25T19:21:46.0242597Z: reading headers [Suave.Web.processRequest]
[V] 2015-11-25T19:21:46.0361531Z: freeing buffer: 794624, free count: 89 [Suave.Web.split] [Suave.Socket.BufferManager]
[V] 2015-11-25T19:21:46.0361531Z: parsing post data [Suave.Web.processRequest]
[V] 2015-11-25T19:21:46.0361531Z: <- processor [Suave.Web.httpLoop.loop]
[V] 2015-11-25T19:21:46.0361531Z: yielding to OWIN middleware [Suave.Owin]
[V] 2015-11-25T19:21:46.0344342Z: reading headers [Suave.Web.processRequest]
[V] 2015-11-25T19:21:46.0361531Z: freeing buffer: 720896, free count: 90 [Suave.Web.split] [Suave.Socket.BufferManager]
[V] 2015-11-25T19:21:46.0361531Z: parsing post data [Suave.Web.processRequest]
[V] 2015-11-25T19:21:46.0361531Z: <- processor [Suave.Web.httpLoop.loop]
[V] 2015-11-25T19:21:46.0361531Z: yielding to OWIN middleware [Suave.Owin]
[V] 2015-11-25T19:21:46.0361531Z: reading headers [Suave.Web.processRequest]
[V] 2015-11-25T19:21:46.0361531Z: freeing buffer: 745472, free count: 91 [Suave.Web.split] [Suave.Socket.BufferManager]
[V] 2015-11-25T19:21:46.0361531Z: parsing post data [Suave.Web.processRequest]
[V] 2015-11-25T19:21:46.0458840Z: <- processor [Suave.Web.httpLoop.loop]
[V] 2015-11-25T19:21:46.0458840Z: yielding to OWIN middleware [Suave.Owin]
[V] 2015-11-25T19:21:46.0242597Z: reading headers [Suave.Web.processRequest]
[V] 2015-11-25T19:21:46.0458840Z: freeing buffer: 761856, free count: 92 [Suave.Web.split] [Suave.Socket.BufferManager]
[V] 2015-11-25T19:21:46.0458840Z: parsing post data [Suave.Web.processRequest]
[V] 2015-11-25T19:21:46.0458840Z: <- processor [Suave.Web.httpLoop.loop]
[V] 2015-11-25T19:21:46.0458840Z: yielding to OWIN middleware [Suave.Owin]
[V] 2015-11-25T19:21:55.3988384Z: freeing buffer: 737280, free count: 93 [Suave.Web.readMoreData] [Suave.Socket.BufferManager]
[V] 2015-11-25T19:21:55.3988384Z: <- processor [Suave.Web.httpLoop.loop]
[V] 2015-11-25T19:21:55.4103841Z: Socket error while sending BAD_REQUEST, exiting: SocketError Shutdown [Suave.Web.httpLoop.loop]
[V] 2015-11-25T19:21:55.4143745Z: freeing buffer: 753664, free count: 94 [Suave.Tcp.tcpIpServer.job] [Suave.Socket.BufferManager]
[V] 2015-11-25T19:21:55.4143745Z: 127.0.0.1 disconnected, total: 5 clients [Suave.Tcp.tcpIpServer.job]
[V] 2015-11-25T19:22:05.4023151Z: freeing buffer: 729088, free count: 95 [Suave.Web.readMoreData] [Suave.Socket.BufferManager]
[V] 2015-11-25T19:22:05.4023151Z: <- processor [Suave.Web.httpLoop.loop]
[V] 2015-11-25T19:22:05.4023151Z: Socket error while sending BAD_REQUEST, exiting: SocketError Shutdown [Suave.Web.httpLoop.loop]
[V] 2015-11-25T19:22:05.4023151Z: freeing buffer: 786432, free count: 96 [Suave.Tcp.tcpIpServer.job] [Suave.Socket.BufferManager]
[V] 2015-11-25T19:22:05.4023151Z: 127.0.0.1 disconnected, total: 4 clients [Suave.Tcp.tcpIpServer.job]
```

**Comment by panesofglass** [comment]
screen shot 2015-11-25 at 1 27 05 pm

**Comment by panesofglass** [comment]
Hmm ... this could require that I add paths not already defined by the `WebSharperAdapter` manually. But why would Suave not be able to handle these paths? Is there something in the OWIN support that isn't able to detect a 404? Or perhaps the WebSharper.Suave and/or OWIN support does not correctly return a 404 for missing files?

**Comment by jeroldhaas** [comment]
@panesofglass My intuition says the latter, for some reason.

**Comment by ademar** [comment]
I haven't looked at the code here but note that Suave does not handle 404
by default; you need to provide a catch-all handler at the end.

On Wednesday, 25 November 2015, Ryan Riley <notifications@github.com> wrote:

> Hmm ... this could require that I add paths not already defined by the
> WebSharperAdapter manually. But why would Suave not be able to handle
> these paths? Is there something in the OWIN support that isn't able to
> detect a 404? Or perhaps the WebSharper.Suave and/or OWIN support does not
> correctly return a 404 for missing files?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/c4fsharp/c4fsharp/pull/1#issuecomment-159715208>.
>


-- 
Ademar Gonzalez
+1-647-891-3606
http://ademar.name
https://github.com/ademar

**Comment by panesofglass** [comment]
@ademar Thanks! I realized that the files all exist, but they weren't mapped via WebSharper, so the server was apparently spinning while waiting. I'll take a look at adding the 404 handler, as well as figuring out how to correctly serve files. I think that's ultimately the issue.

**Comment by Tarmil** [comment]
Yes, WebSharper's adapter only adds a mapping for files that it directly needs, ie. `/Scripts/WebSharper/*` and `/Content/WebSharper/*`. It assumes that you will add your own WebParts for anything else you need, including returning a 404.

**Comment by panesofglass** [comment]
Thanks, @Tarmil. Now to figure out how to host static files without running into the "canonalization issue."

**Comment by haf** [comment]
Here's one example: https://github.com/haf/suave-presentation.2015-09-03/blob/master/src/Site/Program.fs#L220

**Comment by panesofglass** [comment]
@haf, thanks! However, if I use `Files.browse rootDirectory` I get an error:
screen shot 2015-11-25 at 5 12 41 pm

With that last commit, I at least only see the issue returned as a 500 for some static files:
screen shot 2015-11-25 at 5 13 31 pm

**Comment by ademar** [comment]
I think `rootDirectory` need be an absolute path.

**Comment by panesofglass** [comment]
That solved it, @ademar! Thank you!

**Pull request merged**
